# Generated by Django 6.0.3 on 2026-06-13 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_faq_answer_ar_faq_question_ar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingrequest',
            name='notes',
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='end_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookingrequest',
            name='start_time',
            field=models.TimeField(default='00:00:00'),
            preserve_default=False,
        ),
    ]
