# Generated by Django 6.0.3 on 2026-06-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_bookingrequest_notes_bookingrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('12:00', '12:00 PM'), ('14:00', '02:00 PM'), ('16:00', '04:00 PM'), ('18:00', '06:00 PM')], max_length=10),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.CharField(choices=[('10:00', '10:00 AM'), ('12:00', '12:00 PM'), ('14:00', '02:00 PM'), ('16:00', '04:00 PM'), ('18:00', '06:00 PM')], max_length=10),
        ),
    ]
