# Generated by Django 6.0.3 on 2026-06-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_bookingrequest_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('section1', '1st Section'), ('section2', '2nd Section')], default='section1', max_length=50),
        ),
    ]
