# Generated by Django 6.0.3 on 2026-06-21 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_galleryimage_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='celebrationimage',
            options={},
        ),
        migrations.RemoveField(
            model_name='celebrationimage',
            name='order',
        ),
    ]
