# Generated by Django 6.0.3 on 2026-06-21 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_celebrationimage_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('wedding', 'Wedding & Event Planning'), ('floral', 'Floral & Decor Design'), ('vip', 'VIP Hospitality')], max_length=50, unique=True)),
                ('title_en', models.CharField(max_length=255)),
                ('title_ar', models.CharField(max_length=255)),
                ('tagline_en', models.CharField(max_length=255)),
                ('tagline_ar', models.CharField(max_length=255)),
                ('body_en', models.TextField()),
                ('body_ar', models.TextField()),
                ('subheading_en', models.CharField(max_length=255)),
                ('subheading_ar', models.CharField(max_length=255)),
                ('quote_en', models.TextField()),
                ('quote_ar', models.TextField()),
                ('image_left', models.ImageField(upload_to='services/')),
                ('image_right', models.ImageField(upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('section1', '1st Section'), ('section2', '2nd Section'), ('cts', 'CTS Section')], default='section1', max_length=50),
        ),
        migrations.CreateModel(
            name='ServicePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_en', models.CharField(max_length=255)),
                ('point_ar', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='main.servicesection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
