# Generated by Django 6.0.3 on 2026-06-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_servicesection_alter_galleryimage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicesection',
            name='service_type',
            field=models.CharField(choices=[('wedding', 'Wedding & Event Planning'), ('floral', 'Floral & Decor Design'), ('vip', 'VIP Hospitality')], max_length=30, unique=True),
        ),
    ]
