# Generated by Django 6.0.3 on 2026-06-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_servicesection_service_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('card_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=300)),
                ('tagline', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('bullet1', models.CharField(blank=True, max_length=200)),
                ('bullet2', models.CharField(blank=True, max_length=200)),
                ('bullet3', models.CharField(blank=True, max_length=200)),
                ('bullet4', models.CharField(blank=True, max_length=200)),
                ('bullet5', models.CharField(blank=True, max_length=200)),
                ('quote', models.TextField(blank=True)),
                ('card_image', models.ImageField(upload_to='services/cards/')),
                ('left_image', models.ImageField(upload_to='services/details/')),
                ('right_image', models.ImageField(upload_to='services/details/')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(max_length=200)),
                ('title', models.TextField()),
                ('subtitle', models.CharField(max_length=300)),
                ('script', models.CharField(max_length=300)),
            ],
        ),
    ]
