# Generated by Django 6.0.3 on 2026-06-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_mainservice_servicehero'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainservice',
            name='bullet1_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='bullet2_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='bullet3_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='bullet4_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='bullet5_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='card_title_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='description_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='quote_ar',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='tagline_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mainservice',
            name='title_ar',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='bullet1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='bullet2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='bullet3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='bullet4',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='bullet5',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='card_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='tagline',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mainservice',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
