# Generated by Django 6.0.3 on 2026-06-22 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_mainservice_bullet1_ar_mainservice_bullet2_ar_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainservice',
            options={},
        ),
        migrations.RemoveField(
            model_name='mainservice',
            name='order',
        ),
    ]
