# Generated by Django 6.0.3 on 2026-06-22 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_mainservice_options_remove_mainservice_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorporateEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('paragraph1', models.TextField(blank=True)),
                ('paragraph2', models.TextField(blank=True)),
                ('paragraph3', models.TextField(blank=True)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('subtitle_ar', models.CharField(blank=True, max_length=255)),
                ('description_ar', models.TextField(blank=True)),
                ('paragraph1_ar', models.TextField(blank=True)),
                ('paragraph2_ar', models.TextField(blank=True)),
                ('paragraph3_ar', models.TextField(blank=True)),
                ('main_image', models.ImageField(upload_to='corporate/main/')),
                ('side_image', models.ImageField(blank=True, null=True, upload_to='corporate/side/')),
            ],
        ),
    ]
