# Generated by Django 6.0.3 on 2026-06-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_corporateevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='other_services/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
