# Generated by Django 6.0.6 on 2026-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_otherservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(db_index=True, max_length=60)),
                ('element_key', models.CharField(max_length=600)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_ar', models.TextField(blank=True, null=True)),
                ('styles', models.JSONField(blank=True, default=dict)),
                ('image', models.ImageField(blank=True, null=True, upload_to='cms/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['page', 'element_key'],
                'unique_together': {('page', 'element_key')},
            },
        ),
    ]
