# Generated by Django 6.0.6 on 2026-06-22 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_pagecontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='styles_ar',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='styles_en',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
