# Generated by Django 6.0.6 on 2026-06-22 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_pagecontent_styles_ar_pagecontent_styles_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagecontent',
            name='hero_media',
            field=models.FileField(blank=True, null=True, upload_to='cms/hero/'),
        ),
        migrations.AddField(
            model_name='pagecontent',
            name='hero_type',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
