# Generated by Django 6.0.6 on 2026-06-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_pagecontent_hero_media_pagecontent_hero_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryimage',
            name='category',
            field=models.CharField(choices=[('section0', 'Intro Grid (9 images)'), ('section1', '1st Section'), ('section2', '2nd Section'), ('cts', 'CTS Section')], default='section1', max_length=50),
        ),
    ]
