# Generated by Django 6.0.6 on 2026-06-23 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_gallery_section0_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='OffDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('is_full_day', models.BooleanField(default=False)),
                ('start_time', models.CharField(blank=True, max_length=20, null=True)),
                ('end_time', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='end_time',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='start_time',
            field=models.CharField(max_length=20),
        ),
    ]
